kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: falcolab
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./local-plugins
    containerPath: /local-plugins
  - hostPath: ./local-rules
    containerPath: /local-rules
    # allow Falco to use devices provided by the kernel module
  - hostPath: /dev
    containerPath: /dev
    # allow Falco to use the Docker unix socket
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
